

services:
  ubuntu_gpu:
    image: gym_env_docker
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu_gym

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1

    restart: unless-stopped
    network_mode: "host"
    
    devices:
      - /dev/dri

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility, video]

    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix  # Required for GUI apps

    stdin_open: true
    tty: true
